Documentation improvements
exasol/transformers-extension pull request #199
Opened 2024-02-22 13:41 UTC by MarleneKress79789

### All Submissions:

* [ ] Is the title of the Pull Request correct?
* [ ] Is the title of the corresponding issue correct?
* [ ] Have you updated the changelog?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../../pulls) for the same update/change?  
* [ ] Are you mentioning the issue which this PullRequest fixes ("Fixes...")
* [ ] Before you merge don't forget to run tests in AWS CodeBuild, by adding `[CodeBuild]` to the commit message
* Fixes #133 , #188

2024-03-23 01:03 UTC, tkilias requested changes
See my comments and please change the target branch to the dev branch

2024-03-26 12:51 UTC, tkilias commented on pyproject.toml
> +description = "An Exasol extension for using state-of-the-art pretrained machine learning models via the Huggingface transformers api."
```suggestion
description = "An Exasol extension for using state-of-the-art pretrained machine learning models via the Hugging Face Transformers api."
```

2024-03-27 11:23 UTC, MarleneKress79789 commented on buildspec.yml
> -      - poetry run nox -s unit_tests
we already run them in the github ci and running them twice for every commit seems wasteful.

2024-03-27 11:54 UTC, MarleneKress79789 commented on doc/developer_guide/developer_guide.md
> +After you do a Release on the project, you may want to trigger the slc dowload test ***link***
fixed

2024-03-27 12:00 UTC, MarleneKress79789 commented on doc/user_guide/user_guide.md
> +This is not to be confused with the client's own certificate. It may or may not include the private key.
i trusted what mikhail wrote after he experimented with the TE in ai-lab https://github.com/exasol/transformers-extension/pull/150/files/99549de939e855f1698a05a4145d3373f51ffab9#r1392322048

2024-03-27 12:04 UTC, MarleneKress79789 commented on doc/user_guide/user_guide.md
> +        model.save_pretrained(<save_path> / "pretrained" / <model_name>)
changed

2024-03-27 12:06 UTC, MarleneKress79789 commented on doc/user_guide/user_guide.md
> +        model = model_factory.from_pretrained(model_name, cache_dir=<your cache path> / <huggingface model name>)
changed

2024-03-27 12:37 UTC, MarleneKress79789 commented on doc/user_guide/user_guide.md
> +      _PYTHON3_TE_=localzmq+protobuf:///<BUCKETFS_NAME>/<BUCKET_NAME>/<PATH_IN_BUCKET><CONTAINER_NAME>/?\
yes. but if we want to mention that we also need to mention to change it [here](https://github.com/exasol/transformers-extension/blob/main/language_container/exasol_transformers_extension_container/flavor_base/language_definition), right? or is this auto generated and i am not seeing where?

2024-03-27 12:38 UTC, MarleneKress79789 commented on doc/developer_guide/developer_guide.md
> +* filepath: tests/integration_tests/with_db/deployment/test_language_container_deployer_cli.py
chnaged

2024-03-27 12:53 UTC, tkilias commented on doc/user_guide/user_guide.md
> +      _PYTHON3_TE_=localzmq+protobuf:///<BUCKETFS_NAME>/<BUCKET_NAME>/<PATH_IN_BUCKET><CONTAINER_NAME>/?\
good question, lets keep it as for the moment, maybe revisit this later

2024-03-27 12:53 UTC, tkilias commented on doc/user_guide/user_guide.md
> +This is not to be confused with the client's own certificate. It may or may not include the private key.
ok, then keep it, and I need to check later if we support it

2024-03-27 12:54 UTC, tkilias commented on buildspec.yml
> -      - poetry run nox -s unit_tests
ok

2024-04-02 12:09 UTC, MarleneKress79789 commented on doc/user_guide/user_guide.md
> +For example `--nameserver 8.8.8.8` will set it to use Google DNS.
changed

2024-04-02 13:28 UTC, tkilias approved these changes

2024-04-02 13:50 UTC, merged